version: '3.3'
services:
  processing:
    image: processing
    ports:
      - "8100:8100"
    network mode:
      - "host"
    depends on:
      - "storage"
  receiver:
    image: receiver
    ports:
      - "8080:8080"
    depends on:
      - "kafka"
  storage:
    image: storage
    ports:
      - "8090:8090"
    depends on:
      - "kafka"
      - "db"
  audit:
    image: audit
    ports:
      - "8110:8110"
    depends on:
      - "kafka"