openapi: 3.0.0
info:
  description: This is an API for a drink warehouse to help export and import drinks
  version: "1.0.0"
  title: Simple Inventory API
tags:
  - name: admins
    description: import ingredients
  - name: clients
    description: export drinks
paths:
  /inventory/purchase:
    
    get:
      tags:
        - admins
      summary: gets inventory items
      description: gets inventory items after a certain date
      operationId: app.getInventory
      parameters:
        - name: timestamp
          in: query
          description: limits the amount of items on a page
          schema:
            type: string
            format: date-time
            example: 2016-08-29T09:12:33.001Z
      responses:
        '200':
          description: Successfully returned a list of Items
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Drink'
        '400':
          description: Invalid request
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string

  /orders:
    get:
      tags:
        - admins
      summary: gets orders
      description: gets inventory items after a certain date
      operationId: app.getProfit
      parameters:
        - name: timestamp
          in: query
          description: limits the amount of items on a page
          schema:
            type: string
            format: date-time
            example: 2016-08-29T09:12:33.001Z
      responses:
        '200':
          description: Successfully returned a list of orders
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Order'
        '400':
          description: Invalid request
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string

components:
  schemas:
    Drink:
      type: object
      required:
        - name
        - contents
        - price
      properties:
        name:
          type: string
          example: Cola Coka
        price:
          type: number
          example: 25
        contents:
          type: string
          example: water, sugar
    Order:
      required:
        - companyName
        - quantity
        - drink
      properties:
        companyName:
          type: string
          example: McRonalds
        quantity:
          type: integer
          example: 25
        drink:
          type: string
          example: Cola Coka
      type: object